### ISSUE TITLE
下载文件夹时出现错误

### ISSUE THREAD

**Issue by Snakebinp** [zaxtyson/LanZouCloud-CMD#43]
LanZouCloud > Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "lanzou\cmder\downloader.py", line 203, in run
  File "lanzou\api\core.py", line 860, in upload_dir
  File "lanzou\api\core.py", line 587, in mkdir
  File "lanzou\api\core.py", line 652, in get_move_folders
TypeError: 'NoneType' object is not iterable

**Comment by zaxtyson** [comment]
这样的话，试试 mv 命令，看看会不会出错
能分享一下那个文件夹吗，我这边测试一下

**Comment by zaxtyson** [comment]
好像是这个情况 https://github.com/zaxtyson/LanZouCloud-API/issues/18#issue-597678607
上传文件夹出错，试一下 dev 分支的 2.4.5，修复了一下

**Comment by Frankklk** [comment]
确实不会报错了，但是又出现两个新问题，用账号密码登陆不上，用cookies才可以，另外文件夹无法上传，只是上传了一个文件夹的名字
