### ISSUE TITLE
python3 main.py 启动失败

### ISSUE THREAD

**Issue by chenhb23** [zaxtyson/LanZouCloud-CMD#62]
```
正在检测更新...
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    check_update()
  File "/Users/nb/projects/test/LanZouCloud-CMD/lanzou/cmder/utils.py", line 168, in check_update
    tag_name, msg = resp['tag_name'], resp['body']
KeyError: 'tag_name'
```

**Comment by zaxtyson** [comment]
奇怪，理论上不可能出现这个问题🤔。如果网络有问题，会提示异常，停止检查更新。
我这边暂时复现不了，这个问题是偶尔出现还是经常出现呢？换一个网络环境试试呢？

**Comment by chenhb23** [comment]
是网络问题，我开了代理
