### ISSUE TITLE
获取文件列表报错

### ISSUE THREAD

**Issue by chenhb23** [zaxtyson/LanZouCloud-CMD#63]
```
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    commander.login()
  File "/Users/noo/projects/test/LanZouCloud-CMD/lanzou/cmder/cmder.py", line 166, in login
    self.refresh()
  File "/Users/noo/projects/test/LanZouCloud-CMD/lanzou/cmder/cmder.py", line 24, in wrapper
    func(self, *args, **kwargs)
  File "/Users/noo/projects/test/LanZouCloud-CMD/lanzou/cmder/cmder.py", line 105, in refresh
    self._file_list = self._disk.get_file_list(dir_id)
  File "/Users/noo/projects/test/LanZouCloud-CMD/lanzou/api/core.py", line 368, in get_file_list
    resp = resp.json()
  File "/Users/noo/opt/anaconda3/envs/lanzou/lib/python3.8/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/noo/opt/anaconda3/envs/lanzou/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Users/noo/opt/anaconda3/envs/lanzou/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/noo/opt/anaconda3/envs/lanzou/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by zaxtyson** [comment]
根据 #62 的情况看了，可能是你的网络环境有些问题
