### ISSUE TITLE
登录失败 `Error : Expecting value: line 1 column 1 (char 0) `

### ISSUE THREAD

**Issue by chenhb23** [zaxtyson/LanZouCloud-CMD#64]
```

        _                  ______            _____ _                 _
       | |                |___  /           /  __ \ |               | |
       | |     __ _ _ __     / /  ___  _   _| /  \/ | ___  _   _  __| |
       | |    / _  |  _ \   / /  / _ \| | | | |   | |/ _ \| | | |/ _  |
       | |___| (_| | | | | / /__| (_) | |_| | \__/\ | (_) | |_| | (_| |
       \_____/\____|_| |_|\_____/\___/ \____|\____/_|\___/ \____|\____|
      --------------------------------------------------------------------
      Github: https://github.com/zaxtyson/LanZouCloud-CMD (Version: 2.6.7)
      --------------------------------------------------------------------

Info : 下载文件保存路径为: /Users/xxx/Downloads
Info : 使用 setpath 命令可修改保存路径
Info : 其它帮助信息请使用 help 命令查看

自动读取浏览器 Cookie 登录(y):
Info : 请在浏览器端登录账号
Info : 浏览器可能等待几秒才将数据写入磁盘, 请稍等
..........
暂未读取到浏览器数据, 继续扫描(y) :y
..........
暂未读取到浏览器数据, 继续扫描(y) :no
Error : 自动读取 Cookie 失败
> login
自动读取浏览器 Cookie 登录(y): no
Info : 请手动设置 Cookie 内容:
ylogin: 1111111
phpdisk_info: BzFWFVU%2FBT5XbANqCdCAVkADEPsE3VGEAZw84AjJRZFRmA2cNM1NlD2gKWVM%2FVDRRYgs22XD3VsA2NWZQcyVmBVZQVoV2YDMApnWzMFYgA3DggRRZVQ0ADYPPQJiUTFUMwMwDTJTYw86CclTAFQ1UWULZVw6gEFZAM1VmIHMVZgVTA%3D
Error : Expecting value: line 1 column 1 (char 0)
```

**Comment by chenhb23** [comment]
由于登录失败，重新 `python3 main.py` 进去就报错了。如何恢复至未登录状态？

```

        _                  ______            _____ _                 _
       | |                |___  /           /  __ \ |               | |
       | |     __ _ _ __     / /  ___  _   _| /  \/ | ___  _   _  __| |
       | |    / _  |  _ \   / /  / _ \| | | | |   | |/ _ \| | | |/ _  |
       | |___| (_| | | | | / /__| (_) | |_| | \__/\ | (_) | |_| | (_| |
       \_____/\____|_| |_|\_____/\___/ \____|\____/_|\___/ \____|\____|
      --------------------------------------------------------------------
      Github: https://github.com/zaxtyson/LanZouCloud-CMD (Version: 2.6.7)
      --------------------------------------------------------------------

Traceback (most recent call last):
  File "main.py", line 10, in <module>
    commander.login()
  File "/Users/xxx/projects/test/LanZouCloud-CMD/lanzou/cmder/cmder.py", line 120, in login
    self.refresh()
  File "/Users/xxx/projects/test/LanZouCloud-CMD/lanzou/cmder/cmder.py", line 24, in wrapper
    func(self, *args, **kwargs)
  File "/Users/xxx/projects/test/LanZouCloud-CMD/lanzou/cmder/cmder.py", line 105, in refresh
    self._file_list = self._disk.get_file_list(dir_id)
  File "/Users/xxx/projects/test/LanZouCloud-CMD/lanzou/api/core.py", line 368, in get_file_list
    resp = resp.json()
  File "/Users/xxx/opt/anaconda3/envs/lanzou/lib/python3.8/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/xxx/opt/anaconda3/envs/lanzou/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Users/xxx/opt/anaconda3/envs/lanzou/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/xxx/opt/anaconda3/envs/lanzou/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by zaxtyson** [comment]
试试 `logout` 命令

**Comment by chenhb23** [comment]
> 试试 `logout` 命令

`logout` 命令用不了，报完错就自动退出程序了

**Comment by zaxtyson** [comment]
可能是使用了网络代理之类的原因？这位也是类似的问题：#62

**Comment by baisir150** [comment]
我也出现了类似的问题，关闭代理后，问题依然存在，希望作者可以看看。
