### ISSUE TITLE
阿里云ecs Ubuntu 22.04，安装依赖报错

### ISSUE THREAD

**Issue by klzw2233** [zaxtyson/LanZouCloud-CMD#68]
Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [42 lines of output]
      /usr/lib/python3/dist-packages/setuptools/dist.py:723: UserWarning: Usage                                                                                                              of dash-separated 'index-url' will not be supported in future versions. Please u                                                                                                             se the underscore name 'index_url' instead
        warnings.warn(
      /usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResources                                                                                                             DeprecationWarning: 1.1build1 is an invalid version and will not be supported in                                                                                                              a future release
        warnings.warn(
      /usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResources                                                                                                             DeprecationWarning: 0.1.43ubuntu1 is an invalid version and will not be supporte                                                                                                             d in a future release
        warnings.warn(
      /usr/lib/python3/dist-packages/setuptools/installer.py:27: SetuptoolsDepre                                                                                                             cationWarning: setuptools.installer is deprecated. Requirements should be satisf                                                                                                             ied by a PEP 517 installer.
        warnings.warn(
      WARNING: The repository located at mirrors.cloud.aliyuncs.com is not a tru                                                                                                             sted or secure host and is being ignored. If this repository is available via HT                                                                                                             TPS we recommend you use HTTPS instead, otherwise you may silence this warning a                                                                                                             nd allow it anyway with '--trusted-host mirrors.cloud.aliyuncs.com'.
      ERROR: Could not find a version that satisfies the requirement pkgconfig (                                                                                                             from versions: none)
      ERROR: No matching distribution found for pkgconfig
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/setuptools/installer.py", line 82,                                                                                                              in fetch_build_egg
          subprocess.check_call(cmd)
        File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip',                                                                                                              '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpko9cpqcj', '                                                                                                             --quiet', '--index-url', 'http://mirrors.cloud.aliyuncs.com/pypi/simple/', 'pkgc                                                                                                             onfig']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-we7v5wdz/lz4_64529454bc1b480eb924a95d72a66d99/set                                                                                                             up.py", line 154, in <module>
          setup(
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 152,                                                                                                              in setup
          _install_setup_requires(attrs)
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 147,                                                                                                              in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 812, in f                                                                                                             etch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 77                                                                                                             1, in resolve
          dist = best[req.key] = env.best_match(
        File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 10                                                                                                             56, in best_match
          return self.obtain(req, installer)
        File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 10                                                                                                             68, in obtain
          return installer(requirement)
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 883, in f                                                                                                             etch_build_egg
          return fetch_build_egg(self, req)
        File "/usr/lib/python3/dist-packages/setuptools/installer.py", line 84,                                                                                                              in fetch_build_egg
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/usr/bin/python3', '-m', 'pip'                                                                                                             , '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpko9cpqcj',                                                                                                              '--quiet', '--index-url', 'http://mirrors.cloud.aliyuncs.com/pypi/simple/', 'pk                                                                                                             gconfig']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem wit                                                                                                             h pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by klzw2233** [comment]
使用python3.10
